server:
  port: 8000

spring:
  application:
    name: spring-cloud-eureka

eureka:
  client:
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true。
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

